import { Inter } from 'next/font/google';
import './globals.css';
import Header from './_components/Header';
// import { ClerkProvider } from '@clerk/nextjs';
import { Toaster } from './components/ui/sonner';
import { ThemeProvider } from './_components/theme-provider';
import { SocketProvider } from './context/SocketContext';
import { StrictMode } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    // <ClerkProvider>
    <SocketProvider>
      <html lang="en">
        <StrictMode>
          <body className={`${inter.className} bg-white`}>
            {/* <Header /> */}
            {children}
            <Toaster />
          </body>
        </StrictMode>
      </html>
    </SocketProvider>
    // </ClerkProvider>
  );
}
